INSERT INTO role (authority) VALUES ('ROLE_USER');

INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Afghanistan', 'Islamic Republic of Afghanistan', 'AF', 'AS', 'AFG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Åland Islands', 'Åland Islands', 'AX', 'EU', 'ALA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Albania', 'Republic of Albania', 'AL', 'EU', 'ALB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Algeria', 'People''s Democratic Republic of Algeria', 'DZ', 'AF', 'DZA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('American Samoa', 'American Samoa', 'AS', 'OC', 'ASM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Andorra', 'Principality of Andorra', 'AD', 'EU', 'AND');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Angola', 'Republic of Angola', 'AO', 'AF', 'AGO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Anguilla', 'Anguilla', 'AI', 'NA', 'AIA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Antarctica', 'Antarctica (the territory South of 60 deg S)', 'AQ', 'AN', 'ATA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'NA', 'ATG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Argentina', 'Argentine Republic', 'AR', 'SA', 'ARG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Armenia', 'Republic of Armenia', 'AM', 'AS', 'ARM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Aruba', 'Aruba', 'AW', 'NA', 'ABW');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Australia', 'Commonwealth of Australia', 'AU', 'OC', 'AUS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Austria', 'Republic of Austria', 'AT', 'EU', 'AUT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Azerbaijan', 'Republic of Azerbaijan', 'AZ', 'AS', 'AZE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bahamas', 'Commonwealth of the Bahamas', 'BS', 'NA', 'BHS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bahrain', 'Kingdom of Bahrain', 'BH', 'AS', 'BHR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bangladesh', 'People''s Republic of Bangladesh', 'BD', 'AS', 'BGD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Barbados', 'Barbados', 'BB', 'NA', 'BRB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Belarus', 'Republic of Belarus', 'BY', 'EU', 'BLR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Belgium', 'Kingdom of Belgium', 'BE', 'EU', 'BEL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Belize', 'Belize', 'BZ', 'NA', 'BLZ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Benin', 'Republic of Benin', 'BJ', 'AF', 'BEN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bermuda', 'Bermuda', 'BM', 'NA', 'BMU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bhutan', 'Kingdom of Bhutan', 'BT', 'AS', 'BTN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bolivia', 'Republic of Bolivia', 'BO', 'SA', 'BOL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', 'EU', 'BIH');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Botswana', 'Republic of Botswana', 'BW', 'AF', 'BWA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bouvet Island (Bouvetoya)', 'Bouvet Island (Bouvetoya)', 'BV', 'AN', 'BVT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Brazil', 'Federative Republic of Brazil', 'BR', 'SA', 'BRA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('British Indian Ocean Territory (Chagos Archipelago)', 'British Indian Ocean Territory (Chagos Archipelago)', 'IO', 'AS', 'IOT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('British Virgin Islands', 'British Virgin Islands', 'VG', 'NA', 'VGB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Brunei Darussalam', 'Brunei Darussalam', 'BN', 'AS', 'BRN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Bulgaria', 'Republic of Bulgaria', 'BG', 'EU', 'BGR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Burkina Faso', 'Burkina Faso', 'BF', 'AF', 'BFA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Burundi', 'Republic of Burundi', 'BI', 'AF', 'BDI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cambodia', 'Kingdom of Cambodia', 'KH', 'AS', 'KHM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cameroon', 'Republic of Cameroon', 'CM', 'AF', 'CMR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Canada', 'Canada', 'CA', 'NA', 'CAN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cape Verde', 'Republic of Cape Verde', 'CV', 'AF', 'CPV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cayman Islands', 'Cayman Islands', 'KY', 'NA', 'CYM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Central African Republic', 'Central African Republic', 'CF', 'AF', 'CAF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Chad', 'Republic of Chad', 'TD', 'AF', 'TCD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Chile', 'Republic of Chile', 'CL', 'SA', 'CHL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('China', 'People''s Republic of China', 'CN', 'AS', 'CHN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Christmas Island', 'Christmas Island', 'CX', 'AS', 'CXR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CC', 'AS', 'CCK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Colombia', 'Republic of Colombia', 'CO', 'SA', 'COL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Comoros', 'Union of the Comoros', 'KM', 'AF', 'COM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Congo DR', 'Democratic Republic of the Congo', 'CD', 'AF', 'COD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Congo R', 'Republic of the Congo', 'CG', 'AF', 'COG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cook Islands', 'Cook Islands', 'CK', 'OC', 'COK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Costa Rica', 'Republic of Costa Rica', 'CR', 'NA', 'CRI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cote d''Ivoire', 'Republic of Cote d''Ivoire', 'CI', 'AF', 'CIV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Croatia', 'Republic of Croatia', 'HR', 'EU', 'HRV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cuba', 'Republic of Cuba', 'CU', 'NA', 'CUB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Cyprus', 'Republic of Cyprus', 'CY', 'AS', 'CYP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Czech Republic', 'Czech Republic', 'CZ', 'EU', 'CZE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Denmark', 'Kingdom of Denmark', 'DK', 'EU', 'DNK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Djibouti', 'Republic of Djibouti', 'DJ', 'AF', 'DJI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Dominica', 'Commonwealth of Dominica', 'DM', 'NA', 'DMA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Dominican Republic', 'Dominican Republic', 'DO', 'NA', 'DOM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Ecuador', 'Republic of Ecuador', 'EC', 'SA', 'ECU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Egypt', 'Arab Republic of Egypt', 'EG', 'AF', 'EGY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('El Salvador', 'Republic of El Salvador', 'SV', 'NA', 'SLV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Equatorial Guinea', 'Republic of Equatorial Guinea', 'GQ', 'AF', 'GNQ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Eritrea', 'State of Eritrea', 'ER', 'AF', 'ERI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Estonia', 'Republic of Estonia', 'EE', 'EU', 'EST');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ET', 'AF', 'ETH');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Faroe Islands', 'Faroe Islands', 'FO', 'EU', 'FRO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'FK', 'SA', 'FLK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Fiji', 'Republic of the Fiji Islands', 'FJ', 'OC', 'FJI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Finland', 'Republic of Finland', 'FI', 'EU', 'FIN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('France', 'French Republic', 'FR', 'EU', 'FRA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('French Guiana', 'French Guiana', 'GF', 'SA', 'GUF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('French Polynesia', 'French Polynesia', 'PF', 'OC', 'PYF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('French Southern Territories', 'French Southern Territories', 'TF', 'AN', 'ATF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Gabon', 'Gabonese Republic', 'GA', 'AF', 'GAB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Gambia', 'Republic of the Gambia', 'GM', 'AF', 'GMB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Georgia', 'Georgia', 'GE', 'AS', 'GEO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Germany', 'Federal Republic of Germany', 'DE', 'EU', 'DEU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Ghana', 'Republic of Ghana', 'GH', 'AF', 'GHA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Gibraltar', 'Gibraltar', 'GI', 'EU', 'GIB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Greece', 'Hellenic Republic Greece', 'GR', 'EU', 'GRC');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Greenland', 'Greenland', 'GL', 'NA', 'GRL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Grenada', 'Grenada', 'GD', 'NA', 'GRD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guadeloupe', 'Guadeloupe', 'GP', 'NA', 'GLP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guam', 'Guam', 'GU', 'OC', 'GUM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guatemala', 'Republic of Guatemala', 'GT', 'NA', 'GTM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guernsey', 'Bailiwick of Guernsey', 'GG', 'EU', 'GGY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guinea', 'Republic of Guinea', 'GN', 'AF', 'GIN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guinea-Bissau', 'Republic of Guinea-Bissau', 'GW', 'AF', 'GNB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Guyana', 'Co-operative Republic of Guyana', 'GY', 'SA', 'GUY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Haiti', 'Republic of Haiti', 'HT', 'NA', 'HTI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'AN', 'HMD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Holy See (Vatican City State)', 'Holy See (Vatican City State)', 'VA', 'EU', 'VAT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Honduras', 'Republic of Honduras', 'HN', 'NA', 'HND');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Hong Kong', 'Hong Kong Special Administrative Region of China', 'HK', 'AS', 'HKG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Hungary', 'Republic of Hungary', 'HU', 'EU', 'HUN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Iceland', 'Republic of Iceland', 'IS', 'EU', 'ISL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('India', 'Republic of India', 'IN', 'AS', 'IND');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Indonesia', 'Republic of Indonesia', 'ID', 'AS', 'IDN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Iran', 'Islamic Republic of Iran', 'IR', 'AS', 'IRN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Iraq', 'Republic of Iraq', 'IQ', 'AS', 'IRQ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Ireland', 'Ireland', 'IE', 'EU', 'IRL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Isle of Man', 'Isle of Man', 'IM', 'EU', 'IMN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Israel', 'State of Israel', 'IL', 'AS', 'ISR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Italy', 'Italian Republic', 'IT', 'EU', 'ITA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Jamaica', 'Jamaica', 'JM', 'NA', 'JAM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Japan', 'Japan', 'JP', 'AS', 'JPN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Jersey', 'Bailiwick of Jersey', 'JE', 'EU', 'JEY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Jordan', 'Hashemite Kingdom of Jordan', 'JO', 'AS', 'JOR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Kazakhstan', 'Republic of Kazakhstan', 'KZ', 'AS', 'KAZ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Kenya', 'Republic of Kenya', 'KE', 'AF', 'KEN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Kiribati', 'Republic of Kiribati', 'KI', 'OC', 'KIR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Korea DPR', 'Democratic People''s Republic of Korea', 'KP', 'AS', 'PRK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Korea R', 'Republic of Korea', 'KR', 'AS', 'KOR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Kuwait', 'State of Kuwait', 'KW', 'AS', 'KWT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Kyrgyz Republic', 'Kyrgyz Republic', 'KG', 'AS', 'KGZ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Lao People''s Democratic Republic', 'Lao People''s Democratic Republic', 'LA', 'AS', 'LAO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Latvia', 'Republic of Latvia', 'LV', 'EU', 'LVA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Lebanon', 'Lebanese Republic', 'LB', 'AS', 'LBN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Lesotho', 'Kingdom of Lesotho', 'LS', 'AF', 'LSO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Liberia', 'Republic of Liberia', 'LR', 'AF', 'LBR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya', 'LY', 'AF', 'LBY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Liechtenstein', 'Principality of Liechtenstein', 'LI', 'EU', 'LIE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Lithuania', 'Republic of Lithuania', 'LT', 'EU', 'LTU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Luxembourg', 'Grand Duchy of Luxembourg', 'LU', 'EU', 'LUX');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Macao', 'Macao Special Administrative Region of China', 'MO', 'AS', 'MAC');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Macedonia', 'Republic of Macedonia', 'MK', 'EU', 'MKD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Madagascar', 'Republic of Madagascar', 'MG', 'AF', 'MDG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Malawi', 'Republic of Malawi', 'MW', 'AF', 'MWI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Malaysia', 'Malaysia', 'MY', 'AS', 'MYS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Maldives', 'Republic of Maldives', 'MV', 'AS', 'MDV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mali', 'Republic of Mali', 'ML', 'AF', 'MLI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Malta', 'Republic of Malta', 'MT', 'EU', 'MLT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Marshall Islands', 'Republic of the Marshall Islands', 'MH', 'OC', 'MHL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Martinique', 'Martinique', 'MQ', 'NA', 'MTQ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mauritania', 'Islamic Republic of Mauritania', 'MR', 'AF', 'MRT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mauritius', 'Republic of Mauritius', 'MU', 'AF', 'MUS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mayotte', 'Mayotte', 'YT', 'AF', 'MYT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mexico', 'United Mexican States', 'MX', 'NA', 'MEX');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Micronesia', 'Federated States of Micronesia', 'FM', 'OC', 'FSM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Moldova', 'Republic of Moldova', 'MD', 'EU', 'MDA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Monaco', 'Principality of Monaco', 'MC', 'EU', 'MCO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mongolia', 'Mongolia', 'MN', 'AS', 'MNG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Montenegro', 'Republic of Montenegro', 'ME', 'EU', 'MNE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Montserrat', 'Montserrat', 'MS', 'NA', 'MSR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Morocco', 'Kingdom of Morocco', 'MA', 'AF', 'MAR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Mozambique', 'Republic of Mozambique', 'MZ', 'AF', 'MOZ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Myanmar', 'Union of Myanmar', 'MM', 'AS', 'MMR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Namibia', 'Republic of Namibia', 'NA', 'AF', 'NAM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Nauru', 'Republic of Nauru', 'NR', 'OC', 'NRU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Nepal', 'State of Nepal', 'NP', 'AS', 'NPL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Netherlands Antilles', 'Netherlands Antilles', 'AN', 'NA', 'ANT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Netherlands', 'Kingdom of the Netherlands', 'NL', 'EU', 'NLD');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('New Caledonia', 'New Caledonia', 'NC', 'OC', 'NCL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('New Zealand', 'New Zealand', 'NZ', 'OC', 'NZL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Nicaragua', 'Republic of Nicaragua', 'NI', 'NA', 'NIC');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Niger', 'Republic of Niger', 'NE', 'AF', 'NER');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Nigeria', 'Federal Republic of Nigeria', 'NG', 'AF', 'NGA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Niue', 'Niue', 'NU', 'OC', 'NIU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Norfolk Island', 'Norfolk Island', 'NF', 'OC', 'NFK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'MP', 'OC', 'MNP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Norway', 'Kingdom of Norway', 'NO', 'EU', 'NOR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Oman', 'Sultanate of Oman', 'OM', 'AS', 'OMN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Pakistan', 'Islamic Republic of Pakistan', 'PK', 'AS', 'PAK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Palau', 'Republic of Palau', 'PW', 'OC', 'PLW');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Palestinian Territory', 'Occupied Palestinian Territory', 'PS', 'AS', 'PSE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Panama', 'Republic of Panama', 'PA', 'NA', 'PAN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', 'OC', 'PNG');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Paraguay', 'Republic of Paraguay', 'PY', 'SA', 'PRY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Peru', 'Republic of Peru', 'PE', 'SA', 'PER');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Philippines', 'Republic of the Philippines', 'PH', 'AS', 'PHL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Pitcairn Islands', 'Pitcairn Islands', 'PN', 'OC', 'PCN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Poland', 'Republic of Poland', 'PL', 'EU', 'POL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Portugal', 'Portuguese Republic', 'PT', 'EU', 'PRT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Puerto Rico', 'Commonwealth of Puerto Rico', 'PR', 'NA', 'PRI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Qatar', 'State of Qatar', 'QA', 'AS', 'QAT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Reunion', 'Reunion', 'RE', 'AF', 'REU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Romania', 'Romania', 'RO', 'EU', 'ROU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Russian Federation', 'Russian Federation', 'RU', 'EU', 'RUS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Rwanda', 'Republic of Rwanda', 'RW', 'AF', 'RWA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Barthelemy', 'Saint Barthelemy', 'BL', 'NA', 'BLM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Helena', 'Saint Helena', 'SH', 'AF', 'SHN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis', 'KN', 'NA', 'KNA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Lucia', 'Saint Lucia', 'LC', 'NA', 'LCA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Martin', 'Saint Martin', 'MF', 'NA', 'MAF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'PM', 'NA', 'SPM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'NA', 'VCT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Samoa', 'Independent State of Samoa', 'WS', 'OC', 'WSM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('San Marino', 'Republic of San Marino', 'SM', 'EU', 'SMR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', 'ST', 'AF', 'STP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Saudi Arabia', 'Kingdom of Saudi Arabia', 'SA', 'AS', 'SAU');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Senegal', 'Republic of Senegal', 'SN', 'AF', 'SEN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Serbia', 'Republic of Serbia', 'RS', 'EU', 'SRB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Seychelles', 'Republic of Seychelles', 'SC', 'AF', 'SYC');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Sierra Leone', 'Republic of Sierra Leone', 'SL', 'AF', 'SLE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Singapore', 'Republic of Singapore', 'SG', 'AS', 'SGP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Slovakia (Slovak Republic)', 'Slovakia (Slovak Republic)', 'SK', 'EU', 'SVK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Slovenia', 'Republic of Slovenia', 'SI', 'EU', 'SVN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Solomon Islands', 'Solomon Islands', 'SB', 'OC', 'SLB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Somalia', 'Somali Republic', 'SO', 'AF', 'SOM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('South Africa', 'Republic of South Africa', 'ZA', 'AF', 'ZAF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'GS', 'AN', 'SGS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Spain', 'Kingdom of Spain', 'ES', 'EU', 'ESP');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LK', 'AS', 'LKA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Sudan', 'Republic of Sudan', 'SD', 'AF', 'SDN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Suriname', 'Republic of Suriname', 'SR', 'SA', 'SUR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Svalbard & Jan Mayen Islands', 'Svalbard & Jan Mayen Islands', 'SJ', 'EU', 'SJM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Swaziland', 'Kingdom of Swaziland', 'SZ', 'AF', 'SWZ');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Sweden', 'Kingdom of Sweden', 'SE', 'EU', 'SWE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Switzerland', 'Swiss Confederation', 'CH', 'EU', 'CHE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Syrian Arab Republic', 'Syrian Arab Republic', 'SY', 'AS', 'SYR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Taiwan', 'Taiwan', 'TW', 'AS', 'TWN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tajikistan', 'Republic of Tajikistan', 'TJ', 'AS', 'TJK');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tanzania', 'United Republic of Tanzania', 'TZ', 'AF', 'TZA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Thailand', 'Kingdom of Thailand', 'TH', 'AS', 'THA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Timor-Leste', 'Democratic Republic of Timor-Leste', 'TL', 'AS', 'TLS');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Togo', 'Togolese Republic', 'TG', 'AF', 'TGO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tokelau', 'Tokelau', 'TK', 'OC', 'TKL');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tonga', 'Kingdom of Tonga', 'TO', 'OC', 'TON');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', 'NA', 'TTO');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tunisia', 'Tunisian Republic', 'TN', 'AF', 'TUN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Turkey', 'Republic of Turkey', 'TR', 'AS', 'TUR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Turkmenistan', 'Turkmenistan', 'TM', 'AS', 'TKM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Turks and Caicos Islands', 'Turks and Caicos Islands', 'TC', 'NA', 'TCA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Tuvalu', 'Tuvalu', 'TV', 'OC', 'TUV');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Uganda', 'Republic of Uganda', 'UG', 'AF', 'UGA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Ukraine', 'Ukraine', 'UA', 'EU', 'UKR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('United Arab Emirates', 'United Arab Emirates', 'AE', 'AS', 'ARE');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('United Kingdom of Great Britain & Northern Ireland', 'United Kingdom of Great Britain & Northern Ireland', 'GB', 'EU', 'GBR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('United States of America', 'United States of America', 'US', 'NA', 'USA');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'OC', 'UMI');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('United States Virgin Islands', 'United States Virgin Islands', 'VI', 'NA', 'VIR');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Uruguay', 'Eastern Republic of Uruguay', 'UY', 'SA', 'URY');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Uzbekistan', 'Republic of Uzbekistan', 'UZ', 'AS', 'UZB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Vanuatu', 'Republic of Vanuatu', 'VU', 'OC', 'VUT');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Venezuela', 'Bolivarian Republic of Venezuela', 'VE', 'SA', 'VEN');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Vietnam', 'Socialist Republic of Vietnam', 'VN', 'AS', 'VNM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Wallis and Futuna', 'Wallis and Futuna', 'WF', 'OC', 'WLF');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Western Sahara', 'Western Sahara', 'EH', 'AF', 'ESH');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Yemen', 'Yemen', 'YE', 'AS', 'YEM');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Zambia', 'Republic of Zambia', 'ZM', 'AF', 'ZMB');
INSERT INTO country (name, full_name, code, continent_code, iso3) VALUES ('Zimbabwe', 'Republic of Zimbabwe', 'ZW', 'AF', 'ZWE');

INSERT INTO subscription_plan (name, credits_per_month, duration, price_per_month, price_per_year, currencyCode) VALUES ('Free (1 month)', 1, 1, 0, 0, 'NGN');